require:
  - "rubocop-minitest"
  - "rubocop-rake"

AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Style/FormatStringToken:
  EnforcedStyle: unannotated

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120
