# See the writing guide of rbs: https://github.com/ruby/rbs#guides

module Uuidx
  VERSION: String

  type uuid = String

  public

  interface _Generator
    def generate: () -> uuid
  end

  def self.nil_uuid: () -> uuid
  def self.max_uuid: () -> uuid
  def self.v4: () -> uuid
  def self.v6: () -> uuid
  def self.v7: () -> uuid
  def self.batch_v4: (Integer) -> Array[uuid]
  def self.batch_v6: (Integer) -> Array[uuid]
  def self.batch_v7: (Integer) -> Array[uuid]
  def self.reset_v4!: () -> void
  def self.reset_v6!: () -> void
  def self.reset_v7!: () -> void
  def self.batch: (_Generator, Integer) -> Array[uuid]

  private

  def self.format: (Integer) -> uuid
end
